<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ATMECSINLT-601" failures="3" tests="4" name="Test" time="12.059" errors="0" timestamp="2020-11-12T16:01:02 IST">
  <testcase classname="com.atmecs.api_authentication.test.PatchRecord" name="updateUser" time="6.98">
    <failure type="java.lang.AssertionError" message="expected [201] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [200]
at com.atmecs.api_authentication.test.PatchRecord.updateUser(PatchRecord.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- updateUser -->
  <testcase classname="com.atmecs.api_authentication.test.UpdateRecord" name="updateUser" time="1.936">
    <failure type="java.lang.AssertionError" message="expected [201] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [200]
at com.atmecs.api_authentication.test.UpdateRecord.updateUser(UpdateRecord.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- updateUser -->
  <testcase classname="com.atmecs.api_authentication.test.DeleteRecord" name="deleteRecord" time="1.506">
    <failure type="java.lang.AssertionError" message="expected [204] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [204] but found [200]
at com.atmecs.api_authentication.test.DeleteRecord.deleteRecord(DeleteRecord.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- deleteRecord -->
  <testcase classname="com.atmecs.api_authentication.test.GetRecords" name="getApiAuth" time="1.578"/>
</testsuite> <!-- Test -->
